- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Check if binary exists in PATH
      command: which ssh-keygen
      ignore_errors: true
      register: which_out
    - name: Create SSH
      openssh_keypair:
        path: '/tmp/id_ssh_rsa'
      register: ssh_key_local
    
