- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Check if binary exists in PATH
      command: which ssh-keygen
      ignore_errors: true
      register: which_out 
    - name: Hello
      debug:
        msg: "{{ my_var }}"
    - name: Create SSH
      openssh_keypair:
        path: '/tmp/id_ssh_rsa'
      register: ssh_key_local
    - name: Install ansible-pylibssh
      pip:
        name: ansible-pylibssh
        state: present
    - name: Print facts
      debug:
        var: ansible_facts
    
